AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/ios_parser/lexer.rb'
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
