AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Layout/IndentHeredoc:
  EnforcedStyle: unindent

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/ios_parser/lexer.rb'
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/**/*'

Style/CommentedKeyword:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
