language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-9.1.16.0
  - jruby-9.2.0.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='-Xcompat.version=2.0'
bundler_args: --without guard
before_install:
  - if [ "jruby" != "$TRAVIS_RUBY_VERSION"  ]; then gem i rubygems-update -v '<3' && update_rubygems; gem install bundler -v 1.17.3 --without guard; fi
